# Generated by Django 5.1.7 on 2025-04-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlike',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='questionlike',
            table=None,
        ),
    ]
