# Generated by Django 5.1.7 on 2025-04-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_questionlike_is_like_alter_questionlike_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlike',
            name='is_like',
        ),
    ]
