# Generated by Django 5.1.7 on 2025-04-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_questionlike_is_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlike',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='answerlike',
            table=None,
        ),
    ]
